# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Jakarta"
    open-pull-requests-limit: 20
    target-branch: "main"
    labels:
      - "dependencies"
      - "automerge"
      - "npm"
    commit-message:
      prefix: "chore"
      prefix-development: "chore(dev)"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    reviewers:
      - "BOTCAHX"
    rebase-strategy: "auto"
    ignore:
      - dependency-name: "some-risky-package"
        versions: ">= 2.x"
    allow:
      - dependency-type: "production"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:patch"
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
