version = "1"
shortlived_issue = true
autofix = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs"]
  runtime_version = "20.x"
  dialect = "typescript"
  target = "library"
